---
# Production environment override
services:
  php:
    build:
      context: .
      target: frankenphp_prod
    env_file:
      - .env.prod
    environment:
      APP_SECRET: ${APP_SECRET}
      SERVER_NAME: ${SERVER_NAME}, :80
      DEFAULT_URI: ${DEFAULT_URI}
      # JWT & Mailer (required in production)
      JWT_PASSPHRASE: ${JWT_PASSPHRASE}
      JWT_TTL: ${JWT_TTL}
      JWT_REFRESH_TTL: ${JWT_REFRESH_TTL}
      MAILER_DSN: ${MAILER_DSN}
      # Cloudflare R2
      R2_ACCOUNT_ID: ${R2_ACCOUNT_ID}
      R2_ACCESS_KEY_ID: ${R2_ACCESS_KEY_ID}
      R2_SECRET_ACCESS_KEY: ${R2_SECRET_ACCESS_KEY}
      R2_BUCKET: ${R2_BUCKET}
      R2_ENDPOINT: ${R2_ENDPOINT}
      # Disable automatic HTTPS in Caddy; TLS is terminated by Nginx on host
      CADDY_GLOBAL_OPTIONS: auto_https off
    # Persist JWT keys across deployments
    volumes:
      - ./config/jwt:/app/config/jwt
    # Bind HTTP only to localhost:8080 to avoid conflicts with host Nginx/Caddy
    ports:
      - "127.0.0.1:8080:80"

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${PMA_USER:-neooadmin}
      PMA_PASSWORD: ${PMA_PASSWORD:-NeooDriver@9090}
    ports:
      - "127.0.0.1:8081:80"
